version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

#  localstack:
#    image: localstack/localstack
#    ports:
#      - "4566:4566"
#      - "4571:4571"
#    environment:
#      - SERVICES=s3,lambda
#      - DEBUG=1
#    volumes:
#      - "./.localstack:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
